=== OpenDA-Association/OpenDA/core/xmlSchemas/blackBoxModelConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:openda="http://www.openda.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.openda.org" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="blackBoxWrapperConfig.xsd"/>
	<xs:include schemaLocation="blackBoxSharedTypes.xsd"/>
	<xs:complexType name="BlackBoxConfigurableXML">
		<xs:choice>
			<xs:annotation>
				<xs:documentation>Select one of the options, depending on whether a file, sring or arg list is required by this openda:class</xs:documentation>
			</xs:annotation>
			<xs:element name="configFile" type="xs:string">
				<xs:annotation>
					<xs:documentation>Specify the configuration filename</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="configString" type="xs:string">
				<xs:annotation>
					<xs:documentation>Specify the configuration string</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="arg" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Specify the input argument of this openda:class</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
		<xs:attribute name="className" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Specify the openda:class name for performing this operation</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="BlackBoxWrapperConfigReferenceXML">
		<xs:sequence>
			<xs:element name="file" type="xs:string">
				<xs:annotation>
					<xs:documentation>Specify the name of the black box wrapper configuration file, relative to local directory. File format: blackBoxWrapperConfig</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AliasValueXML">
		<xs:sequence>
			<xs:element name="listValue" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>This type of alias can only be used for BBAction arguments, where the argument must be specified	by means of only naming the 'list value' alias. If the listValue element is present, it overrules the value attribute, indicating that the actual value is in fact a list of string arguments instead of one argument.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="key" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The alias key name as defined in the black box wrapper configuration</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string">
			<xs:annotation>
				<xs:documentation>The actual value referred to by the alias key</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="AliasValuesXML">
		<xs:sequence>
			<xs:element name="alias" type="openda:AliasValueXML" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Specify the alias keys and (optionally) the corresponding actual values</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="InstanceNumberFormatXML">
		<xs:annotation>
			<xs:documentation>Specify the format for the numbering of the instance directories. Default is 0: number according the number of digits needed per instance (work0, work112, etc). 00: work02, work07, etcetera, 000: work003, work017, etc.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[0]+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="TimeInfoXML">
		<xs:attribute name="start" type="xs:dateTime" use="optional">
			<xs:annotation>
				<xs:documentation>Specify the start time of the simulation (yyyy-mm-ddThh:mm:ss)</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="end" type="xs:dateTime" use="optional">
			<xs:annotation>
				<xs:documentation>Specify the end time of the simulation (yyyy-mm-ddThh:mm:ss)</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="timeStepInSeconds" type="xs:double" use="optional">
			<xs:annotation>
				<xs:documentation>Specify the time step of the simulation in seconds</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="TimeInfoExchangeItemsXML">
		<xs:attribute name="start" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>The identifier of the exchange item that contains the start time of the simulation</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="end" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>The identifier of the exchange item that contains the end time of the simulation</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="timeStep" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>The identifier of the exchange item that contains the model time step of the simulation</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="BlackBoxIoVectorXML">
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Identity of the exchange item vector to be used in the stochastic model configuration. Note: by using the reserved id "allElementsFromIoObject" all the elements in the data/io object are exposed as exchange items (with the element id in the data/io object as id)</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ioObjectId" type="xs:string">
			<xs:annotation>
				<xs:documentation>Obsolete, please use dataObjectId. The corresponding object identity of the exchange item</xs:documentation>
			</xs:annotation>
		</xs:attribute>
    <xs:attribute name="dataObjectId" type="xs:string">
      <xs:annotation>
        <xs:documentation>The corresponding object identity of the exchange item</xs:documentation>
      </xs:annotation>
    </xs:attribute>
		<xs:attribute name="elementId" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>The corresponding identity of the exchange item as used internally within the model. If this is not specified, then the elementId will be equal to the specified id.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="role" type="openda:BlackBoxModelRoleTypesXML" use="optional" default="InOut">
			<xs:annotation>
				<xs:documentation>The corresponding role type of the exchange item, choose "Input", "Output" or "InOut"</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="idSuffix" type="xs:string">
			<xs:annotation>
				<xs:documentation>Optional. This suffix will be appended to the specified id. If elementId not specified, then the elementId will still be equal to the specified id without this suffix. If id="allElementsFromIoObject", then this suffix will be appended to the ids of all exchangeItems of elements in the ioObject. In that case the elementIds will still be equal to the original ids of the elements in the ioObject, i.e. without this suffix.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="BlackBoxIoSubVectorXML">
		<xs:choice>
			<xs:annotation>
				<xs:documentation>Select one of the options</xs:documentation>
			</xs:annotation>
			<xs:element name="selection" type="openda:IndicesXML">
				<xs:annotation>
					<xs:documentation>Select subvector using indices of the vector elements</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="selector" type="openda:BlackBoxConfigurableXML">
				<xs:annotation>
					<xs:documentation>Define operator for deriving the subvector</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Identity of the exchange item vector to be used in the stochastic model configuration</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ioObjectId" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Obsolete, please use dataObjectId. The corresponding object identity of the exchange item</xs:documentation>
			</xs:annotation>
		</xs:attribute>
    <xs:attribute name="dataObjectId" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The corresponding object identity of the exchange item</xs:documentation>
      </xs:annotation>
    </xs:attribute>
		<xs:attribute name="elementId" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The corresponding identity of the exchange item as used internally within the model</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="role" type="openda:BlackBoxModelRoleTypesXML" use="optional" default="InOut">
			<xs:annotation>
				<xs:documentation>The corresponding role type of the exchange item, choose "Input", "Output" or "InOut"</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ExchangeItemXML">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="vector" type="openda:BlackBoxIoVectorXML">
				<xs:annotation>
					<xs:documentation>Specify vector of the exchange item</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="subVector" type="openda:BlackBoxIoSubVectorXML">
				<xs:annotation>
					<xs:documentation>Specify subvector of the exchange item</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="BlackBoxModelRestartInfoXML">
		<xs:sequence>
			<xs:element name="modelStateFile" type="xs:string" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Specify the file name(s) containing the model state</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="dirPrefix" type="xs:string" use="optional" default="./savedModelState_">
			<xs:annotation>
				<xs:documentation>Specify the prefix of model directory name that will contain a set of restart files for a certain time stamp
				(written when the stoch model level requests to store states, read when the algorithm asks to restore a state)</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="BlackBoxModelConfigXML">
		<xs:sequence>
			<xs:annotation>
				<xs:documentation>Contains the elements in fixed order of occurrence</xs:documentation>
			</xs:annotation>
			<xs:element name="wrapperConfig" type="openda:BlackBoxWrapperConfigReferenceXML">
				<xs:annotation>
					<xs:documentation>Specify black box wrapper configuration that addresses the deterministic model</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="aliasValues" type="openda:AliasValuesXML">
				<xs:annotation>
					<xs:documentation>Specify the actual values referred to by the alias keys defined in the black box wrapper configuration</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="instanceNumberFormat" type="openda:InstanceNumberFormatXML" minOccurs="0" default="0"/>
			<xs:choice minOccurs="0">
				<xs:annotation>
					<xs:documentation>Select one of the options</xs:documentation>
				</xs:annotation>
				<xs:element name="timeInfo" type="openda:TimeInfoXML">
					<xs:annotation>
						<xs:documentation>Specify the time information of the simulation (optional)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="timeInfoExchangeItems" type="openda:TimeInfoExchangeItemsXML" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Specify the time information of the simulation in terms of ioObject exchange item id's (optional). Multiple timeInfoExchangeItems can be specified, each one with a unique id. This is needed if there are multiple ioObjects that have exchangeItems for the start and/or end time.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:choice>
			<xs:element name="exchangeItems" type="openda:ExchangeItemXML">
				<xs:annotation>
					<xs:documentation>Specify the list of items to exchange between the model and OpenDA components. An exchange item may be defined either as vector or subvector.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="doCleanUp" type="xs:boolean" default="false" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Specify whether to remove unnecessary files upon completion of a model run (boolean, optional)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="skipModelActionsIfInstanceDirExists" type="xs:boolean" default="false" minOccurs="0">
				<xs:annotation>
					<xs:documentation>If set to true, no actions are executed on a model instance that already exists (boolean, optional)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="restartInfo" type="openda:BlackBoxModelRestartInfoXML" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Restart dir./files information.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="blackBoxModelConfig" type="openda:BlackBoxModelConfigXML">
		<xs:annotation>
			<xs:documentation>Configuration for a black box model. Here the reference to a specific model configuration is made.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:simpleType name="BlackBoxModelRoleTypesXML">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Input"/>
			<xs:enumeration value="InOut"/>
			<xs:enumeration value="Output"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== OpenDA-Association/OpenDA/course/exercise_black_box_calibration_polution_NOT_WORKING/stochModel/polluteModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<blackBoxModelConfig xmlns="http://www.openda.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.openda.org http://schemas.openda.org/blackBoxModelConfig.xsd">

	<!-- Specify wrapper configuration for which this model is defined -->
	<wrapperConfig>
		<file>polluteWrapper.xml</file>
	</wrapperConfig>

	<!-- Specify wrapper configuration for which this model is defined -->
	<aliasValues>
		<alias key="templateDir"   value="template" />
		<alias key="instanceDir"   value="../work/work" />
		<alias key="binDir"        value="bin" />
		<alias key="inputFile"     value="reactive_pollution_model.input" />
		<alias key="configFile"    value="config.yaml" />
		<alias key="inputFileC1"   value="input/concentration1.txt" />
		<alias key="inputFileC2"   value="input/concentration2.txt" />
		<alias key="outputFile"    value="reactive_pollution_model.output" />
		<alias key="restartFileC1" value="restart/concentration1.txt" />
		<alias key="restartFileC2" value="restart/concentration2.txt"/>
	</aliasValues>

    <!--  <timeInfoExchangeItems start="" end="" /> -->
    <!-- <timeInfo start="1999-12-01T01:00:00" end="1999-12-01T02:00:00" timeStepInSeconds="120"/> -->
    <timeInfoExchangeItems start="start_time" timeStep="time_step" end="end_time"/>

	<exchangeItems>
		<vector id="source.factory1.discharge" ioObjectId="forcings"             elementId="source.c1_factory1.discharge" />
		<vector id="source.factory2.discharge" ioObjectId="forcings"             elementId="source.c1_factory2.discharge" />
		<vector id="concentration1.grid"       ioObjectId="state_concentration1" elementId="concentration1" />
		<vector id="concentration2.grid"       ioObjectId="state_concentration2" elementId="concentration2" />
		<vector id="reaction_time"             ioObjectId="configuration"        elementId="reaction_time" />
		<vector id="start_time"                ioObjectId="configuration"        elementId="time_control@1" />
		<vector id="time_step"                 ioObjectId="configuration"        elementId="time_control@2" />
		<vector id="end_time"                  ioObjectId="configuration"        elementId="time_control@3" />
		<vector id="locA.concentration1"       ioObjectId="output"               elementId="model.locA.concentration1" />
		<vector id="locB.concentration1"       ioObjectId="output"               elementId="model.locB.concentration1" />
		<vector id="locC.concentration1"       ioObjectId="output"               elementId="model.locC.concentration1" />
		<vector id="locA.concentration2"       ioObjectId="output"               elementId="model.locA.concentration2" />
		<vector id="locB.concentration2"       ioObjectId="output"               elementId="model.locB.concentration2" />
		<vector id="locC.concentration2"       ioObjectId="output"               elementId="model.locC.concentration2" />
	</exchangeItems>

	<doCleanUp>false</doCleanUp>

</blackBoxModelConfig>

=== OpenDA-Association/OpenDA/model_delft3d/tests/d3d_3Dlake_EnKF_states/stochModel/D3DModel.xml
<?xml version="1.0" encoding="UTF-8"?>
    <blackBoxModelConfig xmlns="http://www.openda.org"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.openda.org http://schemas.openda.org/blackBoxModelConfig.xsd">

   <!-- Specify wrapper configuration for which this model is defined -->
   <wrapperConfig>
      <file>D3DWrapper.xml</file>
   </wrapperConfig>

   <!-- Specify wrapper configuration for which this model is defined -->
   <aliasValues>
      <alias key="templateDir" value="./model"/>
      <alias key="instanceDir" value="./work"/>
      <alias key="runid" value="cadagno_netcdf"/>
      <alias key="exedir" value="C:\Program Files (x86)\Deltares\delft3d_ohmw_4.01.01.rc.03\delft3d\win32\flow2d3d\bin"/>
      <alias key="linexedir" value="/opt/delft3d_v6/lnx64/flow2d3d/bin"/>
	</aliasValues>

<!-- Specify the time interval  NOTE one hour difference!!!!, openDA error!!!-->
 <!--   <timeInfo start="2015-06-01T00:00:00" end="2015-06-03T00:00:00" /> -->
	<timeInfoExchangeItems start="Tstart" end ="Tstop"/>

   <exchangeItems>

		<!--Wind Component-->
		<vector id="windu" ioObjectId="windwuFile"></vector>
		<vector id="windv" ioObjectId="windwvFile"></vector>

		<vector id="S1" ioObjectId="states" elementId="S1"/>
		<vector id="U1" ioObjectId="states" elementId="U1"/>
		<vector id="V1" ioObjectId="states" elementId="V1"/>
		<vector id="R1" ioObjectId="states" elementId="R1"/>

		<vector id="Tstart" ioObjectId="mdFile"></vector>
		<vector id="Tstop" ioObjectId="mdFile"></vector>

		<vector id="station1.temperature" ioObjectId="trih-file" elementId="station1.GRO.lay-20"/>
		<vector id="station2.temperature" ioObjectId="trih-file" elementId="station2.GRO.lay-20"/>
		<vector id="station3.temperature" ioObjectId="trih-file" elementId="station3.GRO.lay-20"/>
		<vector id="station4.temperature" ioObjectId="trih-file" elementId="station4.GRO.lay-20"/>

    </exchangeItems>

   <doCleanUp>false</doCleanUp>

</blackBoxModelConfig>

=== OpenDA-Association/OpenDA/model_delft3d/tests/d3d_3Dlake_calibration/stochModel/D3DModel_netcdf.xml
<?xml version="1.0" encoding="UTF-8"?>
    <blackBoxModelConfig xmlns="http://www.openda.org"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.openda.org http://schemas.openda.org/blackBoxModelConfig.xsd">

   <!-- Specify wrapper configuration for which this model is defined -->
   <wrapperConfig>
      <file>D3DWrapper.xml</file>
   </wrapperConfig>

   <!-- Specify wrapper configuration for which this model is defined -->
   <aliasValues>
      <alias key="templateDir" value="./model"/>
      <alias key="instanceDir" value="../work/work"/>
      <alias key="runid" value="cadagno_netcdf"/>
      <alias key="exedir" value="C:\Program Files (x86)\Deltares\delft3d_ohmw_4.01.01.rc.03\delft3d\win32\flow2d3d\bin"/>
   </aliasValues>

<!-- Specify the time interval  NOTE one hour difference!!!!, openDA error!!!-->
 <!--   <timeInfo start="2015-06-01T00:00:00" end="2015-06-03T00:00:00" /> -->

   <exchangeItems>

      <vector id="Stantn" ioObjectId="mdFile"></vector>

      <vector id="station1.GRO.lay-20" ioObjectId="trih-file" elementId="station1.GRO.lay-20"/>
      <vector id="station2.GRO.lay-20" ioObjectId="trih-file" elementId="station2.GRO.lay-20"/>
      <vector id="station3.GRO.lay-20" ioObjectId="trih-file" elementId="station3.GRO.lay-20"/>
      <vector id="station4.GRO.lay-20" ioObjectId="trih-file" elementId="station4.GRO.lay-20"/>

    </exchangeItems>

   <doCleanUp>false</doCleanUp>

</blackBoxModelConfig>

=== OpenDA-Association/OpenDA/model_dflowfm_blackbox/tests/estuary_kalman_FMSuite2019.01_bcfile/stochModel/dflowfmModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<blackBoxModelConfig xmlns="http://www.openda.org" 
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                     xsi:schemaLocation="http://www.openda.org http://schemas.openda.org/blackBoxModelConfig.xsd">
	<!-- Specify wrapper configuration for which this model is defined -->
	<wrapperConfig>
		<file>dflowfmWrapper.xml</file>
	</wrapperConfig>

	<!-- Specify wrapper configuration for which this model is defined -->
	<aliasValues>
		<alias key="exedir" value="./bin"/> 
		<alias key="instanceDir" value="./work"/>
		<alias key="templateDir" value="./input_dflowfm"/>
		<alias key="mdufile" value="dflowfm/estuary.mdu"/>
		<alias key="hisfile" value="dflowfm/DFM_OUTPUT_estuary/estuary_his.nc"/>
		<alias key="concatenated_hisfile" value="full_estuary_his.nc"/>
		<alias key="mapfile" value="dflowfm/estuary_map.nc"/>
		<alias key="mapfile_out" value="dflowfm/DFM_OUTPUT_estuary/estuary_map.nc"/>
	</aliasValues>

    <timeInfoExchangeItems start="start_time" end="end_time"/>

    <exchangeItems>
        <vector id="allElementsFromIoObject" ioObjectId="bcfile"/>
        <vector id="start_time" ioObjectId="mdufile" elementId="start_time" />
        <vector id="end_time" ioObjectId="mdufile" elementId="end_time" />
        <vector id="s1" ioObjectId="mapfile" elementId="s1"/>
        <vector id="s0" ioObjectId="mapfile" elementId="s0"/>
        <vector id="unorm" ioObjectId="mapfile" elementId="unorm"/>
        <vector id="u0" ioObjectId="mapfile" elementId="u0"/>	
        <vector id="station01.waterlevel" ioObjectId="hisfile" elementId="station01.waterlevel"/>
        <vector id="station02.waterlevel" ioObjectId="hisfile" elementId="station02.waterlevel"/>
        <vector id="station03.waterlevel" ioObjectId="hisfile" elementId="station03.waterlevel"/>
    </exchangeItems>

<doCleanUp>false</doCleanUp>

</blackBoxModelConfig>

=== OpenDA-Association/OpenDA/core/java/test/org/openda/blackbox/wrapper/testData/restart/bbModelConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<blackBoxModelConfig xmlns="http://www.openda.org"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="http://www.openda.org
			http://schemas.openda.org/blackBoxModelConfig.xsd">

    <wrapperConfig>
        <file>bbWrapperConfig.xml</file>
    </wrapperConfig>

    <!-- Specify wrapper configuration for which this model is defined -->
    <aliasValues>
        <alias key="templateDir" value="./model"/>
        <alias key="instanceDir" value="./work"/>
    </aliasValues>

    <exchangeItems>
        <vector id="allElementsFromIoObject" ioObjectId="state"/>
    </exchangeItems>

	<instanceNumberFormat>000</instanceNumberFormat>

    <doCleanUp>false</doCleanUp>

    <restartInfo>
        <!-- files relative to instance dir -->
        <modelStateFile>dflow1d/wlevStateFileIn.xyz</modelStateFile>
        <modelStateFile>dflow1d/sobek.rda</modelStateFile>
        <modelStateFile>dflow1d/sobek.rdf</modelStateFile>
        <modelStateFile>dflow1d/extra/extra.txt</modelStateFile>
        <modelStateFile>rtc/state_export.xml</modelStateFile>
    </restartInfo>

</blackBoxModelConfig>

=== OpenDA-Association/OpenDA/model_delft3d/java/test/org/openda/model_delft3d/testData/bb_test_1/stochModel/config/d3dBbModelConfig_linux64_gnu.xml
<?xml version="1.0" encoding="UTF-8"?>
<blackBoxModelConfig xmlns="http://www.openda.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openda.org http://www.openda.org/schemas/blackBoxModelConfig.xsd">

	<!-- Specify wrapper configuration for which this model is defined -->
	<wrapperConfig>
		<file>d3dBbWrapperConfig_linux64_gnu.xml</file>
	</wrapperConfig>

	<!-- Specify wrapper configuration for which this model is defined -->
	<aliasValues>
		<alias key="templateDir" value="../model"/>
		<alias key="instanceDir" value="../work"/>
		<alias key="runid" value="f34"/>
	</aliasValues>

    <timeInfo start="1990-08-06T00:00:00" end="1990-08-06T01:00:00"/>

	<exchangeItems>

        <vector id="ne1a.M4.Phase" ioObjectId="astro-components"/>
        <vector id="ne1a.M4.Amplitude" ioObjectId="astro-components"/>
        <vector id="ne1a.M2.Phase" ioObjectId="astro-components"/>
        <vector id="ne1a.M2.Amplitude" ioObjectId="astro-components"/>
        <vector id="ne1a.K1.Amplitude" ioObjectId="astro-components"/>
        <vector id="ne1b.K1.Amplitude" ioObjectId="astro-components"/>

        <vector id="depth" ioObjectId="depth"/>
        <vector id="H-W1" ioObjectId="trih-file" elementId="W1.water level"/>
        <vector id="H-W2" ioObjectId="trih-file" elementId="W2.water level"/>
        <vector id="H-W3" ioObjectId="trih-file" elementId="W3.water level"/>
        <vector id="H-W4" ioObjectId="trih-file" elementId="W4.water level"/>
        <vector id="H-W5" ioObjectId="trih-file" elementId="W5.water level"/>
    </exchangeItems>

	<doCleanUp>false</doCleanUp>

</blackBoxModelConfig>
