=== OpenDA-Association/OpenDA/core/xmlSchemas/blackBoxWrapperConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:openda="http://www.openda.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.openda.org" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="AliasDefinitionXML">
		<xs:sequence>
			<xs:element name="listValue" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>This type of alias can only be used for BBAction arguments, where the argument must be specified	by means of only naming the 'list value' alias. If the listValue element is present, it overrules the value attribute, indicating that the actual value is in fact a list of string arguments instead of one argument.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="key" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The alias key name</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Actual value referred to by the alias key</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="keyPrefix" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Specify the prefix for the alias key</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="keySuffix" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Specify the suffix for the alias key</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="AliasDefinitionsXML">
		<xs:sequence>
			<xs:element name="alias" type="openda:AliasDefinitionXML" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Create list of aliases containing keys and (optional) the corresponding values</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="defaultKeyPrefix" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Specify the default prefix for the alias keys</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="defaultKeySuffix" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Specify the default suffix for the alias keys</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ActionXML">
		<xs:sequence>
			<xs:element name="arg" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Specify list of  input arguments of the model executable</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="checkOutput" type="openda:CheckOutputXML" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Specify list of output files to be checked after the command execution has finished</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="checkReturnStatus" type="openda:CheckReturnStatusXML" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Specify return value after the command execution has finished</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="exe" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Name and path of the executable file</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="windowsExe" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Name and path of the executable file for Windows operating system</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="linuxExe" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Name and path of the executable file for Linux operating system</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="macExe" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Name and path of the executable file for Mac operating system</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="className" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>The openda:class name.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="workingDirectory" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Directory where executable file is run. This is usually the instance dir. This is only used in blackBoxStochModelConfig.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="actualWorkingDirectory" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Subdirectory of instance dir, where executable file has to be run. To be specified as relative path to instance dir. This is only used in blackBoxWrapperConfig. This is only used for executable files, not for Java classes. For Java classes the instanceDir is used as workingDirectory.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ignoreStatus" type="xs:boolean" use="optional" default="false">
			<xs:annotation>
				<xs:documentation>Flag for ignoring the status of the previous action step (ignoreStatus=true). Not yet implemented.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="CheckOutputXML">
		<xs:attribute name="file" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Name of output file</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="expect" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Expected content of the output file when the action is successful</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="CheckReturnStatusXML">
		<xs:attribute name="expect" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Expected return value when the action is successful</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="CloneFileXML">
		<xs:attribute name="templateFile" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="CloneDirXML">
		<xs:attribute name="templateDir" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="ActionsXML">
		<xs:sequence>
			<xs:element name="action" type="openda:ActionXML" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Specify the consecutive actions  by model executables or classes to run, arguments to supply and fail/success checks to perform</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="InitialActionsDirCloneXML">
		<xs:sequence>
			<xs:element name="action" type="openda:ActionXML" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Specify the consecutive actions  by model executables or classes to run, arguments to supply and fail/success checks to perform</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="templateDir" type="xs:string">
			<xs:annotation>
				<xs:documentation>Directory where the template files are stored</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="instanceDir" type="xs:string">
			<xs:annotation>
				<xs:documentation>The working directory where the template directory will be copied into</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="InitialActionsFileCloneXML">
		<xs:sequence>
			<xs:element name="action" type="openda:ActionXML" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Specify the consecutive actions  by model executables or classes to run, arguments to supply and fail/success checks to perform</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="templateFile" type="xs:string">
			<xs:annotation>
				<xs:documentation>Name of the template file.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="instanceFile" type="xs:string">
			<xs:annotation>
				<xs:documentation>File name of the instance of the template file.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="IoObjectXML">
		<xs:sequence>
			<xs:element name="file" type="xs:string">
				<xs:annotation>
					<xs:documentation>Name of input/output file</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="id" type="xs:string">
				<xs:annotation>
					<xs:documentation>Identity of the input/output object</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="arg" type="xs:string" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Input argument for the corresponding openda:class</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="className" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Obsolete, please use DataObjectXML. The openda:class name of the input/output object</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
  <xs:complexType name="DataObjectXML">
    <xs:sequence>
      <xs:element name="file" type="xs:string">
        <xs:annotation>
          <xs:documentation>Name of input/output file</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="id" type="xs:string">
        <xs:annotation>
          <xs:documentation>Identity of the input/output object</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="arg" type="xs:string" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Input argument for the corresponding openda:class</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="className" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The openda:class name of the input/output data object</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
	<xs:complexType name="InputOutputXML">
		<xs:sequence>
			<xs:element name="ioObject" type="openda:IoObjectXML" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Obsolete, please use dataObject. Specify the input/output object</xs:documentation>
				</xs:annotation>
			</xs:element>
      <xs:element name="dataObject" type="openda:DataObjectXML" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Specify the input/output data object</xs:documentation>
        </xs:annotation>
      </xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BlackBoxWrapperRunXML">
		<xs:sequence>
			<xs:choice>
				<xs:annotation>
					<xs:documentation>Configure method for model initialization. Select one of the three options.</xs:documentation>
				</xs:annotation>
				<xs:element name="initializeActions" type="openda:ActionsXML">
					<xs:annotation>
						<xs:documentation>Generic method of initialization actions</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="initializeActionsUsingDirClone" type="openda:InitialActionsDirCloneXML">
					<xs:annotation>
						<xs:documentation>The directory, in which the model executables and input files are located, will be copied to a new working directory. The actions are executed in this new working directory.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="initializeActionsUsingFileClone" type="openda:InitialActionsFileCloneXML">
					<xs:annotation>
						<xs:documentation>Some of the model files (template) will be copied to the working directory where the actions will be executed</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:choice>
			<xs:element name="computeActions" type="openda:ActionsXML">
				<xs:annotation>
					<xs:documentation>Configure the method for model computation</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="additionalComputeActions" type="openda:ActionsXML" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Configure the actions that should be performed after all other computation actions (used for instance when the actual computation is sent to a queue. The additional computation action can then be used to start a script that checks the status of the queue.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="finalizeActions" type="openda:ActionsXML">
				<xs:annotation>
					<xs:documentation>Configure the method for model finalization</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BlackBoxWrapperConfigXML">
		<xs:sequence>
			<xs:element name="aliasDefinitions" type="openda:AliasDefinitionsXML">
				<xs:annotation>
					<xs:documentation>Define aliases for specific model information (directory names, file names etc.). Specify the prefix and suffix for the alias keys.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="run" type="openda:BlackBoxWrapperRunXML">
				<xs:annotation>
					<xs:documentation>Specify the initialize, compute and finalize actions that direct the model</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="inputOutput" type="openda:InputOutputXML">
				<xs:annotation>
					<xs:documentation>Specify the list of input/output objects</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="blackBoxWrapperConfig" type="openda:BlackBoxWrapperConfigXML">
		<xs:annotation>
			<xs:documentation>Configuration of a black box model wrapper. It contains of three main components: alias definitions, model run, and input-output definition.</xs:documentation>
		</xs:annotation>
	</xs:element>
</xs:schema>

=== OpenDA-Association/OpenDA/model_delft3d/java/test/org/openda/model_delft3d/testData/test_4/stochmodel/D3DWrapperConfig_linux64_gnu.xml
<?xml version="1.0" encoding="UTF-8"?>
<blackBoxWrapperConfig xmlns="http://www.openda.org"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="http://www.openda.org http://www.schemas.openda.org/blackBoxWrapperConfig.xsd">

	<!-- declare all the used aliases, specify the prefix and suffix of an alias key in a variable  -->
	<aliasDefinitions defaultKeyPrefix="%" defaultKeySuffix="%" >
		<alias key="D3D_HOME" />
		<alias key="NATIVE_DLL_DIR" value="../../../../../../../../model_delft3d/native_bin/linux64_gnu/lib/libODS.so.0.0.0" />
		<alias key="instanceDir"/>
		<alias key="templateDir" value="../model"/>
		<alias key="runid"/>
		<alias key="roughness"/>
        <alias key="exedir"/>
    </aliasDefinitions>

	<run>

		<!-- for each model instance, the template directory will be cloned to create the instance directory -->
		<initializeActionsUsingDirClone instanceDir="%instanceDir%%instanceNumber%" templateDir="%templateDir%"/>

		<!-- computation actions -->
		<!-- define actions relative to working dir. -->
		<computeActions>
			<action workingDirectory="%instanceDir%" linuxExe="%exedir%/d_hydro.exe" >
				<arg>config_d_hydro.xml</arg>
			</action>
		</computeActions>
		<!--additionalComputeActions>
			<action workingDirectory="%instanceDir%" linuxExe="%OPENDADIR%/delftFlowRunWait.sh">
				<arg>%runid%</arg>
				<arg>%runid%_%instanceNumber%</arg>
			</action>
		</additionalComputeActions-->

		<!-- actions to finalize (e.g. cleanup) an instance -->
		<finalizeActions/>

	</run>

	<inputOutput>

	<!-- astro -->
		<ioObject className="org.openda.model_delft3d.D3dAstroComponentFiles">
			<file>%runid%.mdf</file>
		<id>astro-components</id>
	</ioObject>

		<!-- u/v rougness -->
		<ioObject className="org.openda.model_delft3d.D3dField2DFile">
			<file>%runid%.mdf</file>
			<id>roughness</id>
			<arg>rgh</arg>
		</ioObject>


		<!-- depth -->
		<ioObject className="org.openda.model_delft3d.D3dField2DFile">
			<file>%runid%.mdf</file>
			<id>depth</id>
			<arg>dep</arg>
		</ioObject>

		<!-- wind, u- direction -->
		<ioObject className="org.openda.model_delft3d.D3dWindFile">
			<file>%runid%.mdf</file>
			<id>windguFile</id>
			<arg>gu</arg>
		</ioObject>

		<!-- wind, v- direction -->
		<ioObject className="org.openda.model_delft3d.D3dWindFile">
			<file>%runid%.mdf</file>
			<id>windgvFile</id>
			<arg>gv</arg>
		</ioObject>

		<!-- time series results -->
		<ioObject className="org.openda.model_delft3d.D3dResults">
			<file>trih-%runid%.dat</file>
			<id>trih-file</id>
			<arg>%NATIVE_DLL_DIR%</arg>
		</ioObject>
	</inputOutput>

</blackBoxWrapperConfig>

=== OpenDA-Association/OpenDA/model_swan/java/test/org/openda/model_swan/testData/SwanSimpleBBEnKF/stochModel/bbSwanWrapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<blackBoxWrapperConfig xmlns="http://www.openda.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openda.org http://schemas.openda.org/blackBoxWrapperConfig.xsd">

	<aliasDefinitions defaultKeyPrefix="%" defaultKeySuffix="%" >
		<alias key="SWANDIR"/>
		<alias key="templateDir"/>
		<alias key="instanceDir"/>
		<alias key="inputFile"/>
		<alias key="hotFile"/>
		<alias key="windFile"/>
		<alias key="openboundaryFile"/>
        <alias key="outFile"/>
	</aliasDefinitions>

	<run>

		<!-- for each model instance, the template directory will be cloned to create the instance directory -->
		<initializeActionsUsingDirClone instanceDir="%instanceDir%%instanceNumber%" templateDir="%templateDir%"/>

		<computeActions>
            <action workingDirectory="%instanceDir%" windowsExe="%SWANDIR%/bin/win32/copyInput.bat" linuxExe="%SWANDIR%/bin/linux/copyInput.sh" macExe="%SWANDIR%/bin/darwin/copyInput.sh"/>
			<action workingDirectory="%instanceDir%" windowsExe="%SWANDIR%/bin/win32/swan_4081_del_w32_i11_omp.exe" linuxExe="%SWANDIR%/bin/linux/swan_4072ABCDE_del_l64_i11_ser.exe" macExe="%SWANDIR%/bin/darwin/swan_4072ABCDE_del_l32_i11_ser.exe"/>
		</computeActions>

		<finalizeActions/>

	</run>


<inputOutput>

    <dataObject className="org.openda.model_swan.SwanOpenBoundaryTPARFile">
		<file>%openboundaryFile%</file>
		<id>openBoundary</id>
		<arg></arg>
    </dataObject>

    <!--
    <dataObject className="org.openda.model_swan.SwanField2DXYFile">
		<file>%windFile%</file>
		<id>windFile</id>
		 <arg>%inputFile%</arg>
         <arg>WIND</arg>
    </dataObject>
    -->

    <dataObject className="org.openda.model_swan.SwanStateFile">
            <file>%hotFile%</file>
            <id>hotFile</id>
            <arg></arg>
    </dataObject>

    <dataObject className="org.openda.model_swan.SwanResultsTimeDependent">
            <file>%outFile%</file>
            <id>outFile</id>
            <arg></arg>
    </dataObject>

    <dataObject className="org.openda.model_swan.SwanTimeInfo">
            <file>%inputFile%</file>
            <id>timeInfo</id>
            <arg></arg>
    </dataObject>

</inputOutput>

</blackBoxWrapperConfig>

=== OpenDA-Association/OpenDA/model_gotm/tests/gotm_simple_kalman/stochModel/gotmWrapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<blackBoxWrapperConfig xmlns="http://www.openda.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.openda.org http://www.openda.org/schemas/openda_1.0/blackBoxWrapperConfig.xsd">

	<aliasDefinitions defaultKeyPrefix="%"
		defaultKeySuffix="%">
		<alias key="binDir" />
		<alias key="templateDir" />
		<alias key="instanceDir" />
		<alias key="outputFile" />
		<alias key="outputTemp" />
		<alias key="outputSalt" />
		<alias key="outputEps" />
		<alias key="outputVelo" />
		<alias key="outputMeanTop" />
		<alias key="outputMeanMid" />
		<alias key="outputMeanBot" />
		<alias key="meanVar" />
		<alias key="meanDepth" />
		<alias key="inputFile" />
		<alias key="inputFileTurb" />
		<alias key="inputFileMeteo" />
	</aliasDefinitions>

	<run>

		<!--
			for each model instance, the template directory will be cloned to
			create the instance directory
		-->
		<initializeActionsUsingDirClone
			instanceDir="%instanceDir%%instanceNumber%" templateDir="%templateDir%" />

		<computeActions>
			<action linuxExe="run_GOTM.sh" windowsExe="run_GOTM.bat" workingDirectory="%instanceDir%">
				<checkOutput file="%outputFile%" /> <!-- should exist -->
			</action>
		</computeActions>

		<additionalComputeActions>
                <!-- write restart files -->
                <action exe="saveStep.sh"  workingDirectory="%instanceDir%">
                        <arg></arg>
                </action>
                <action exe="../bin/profile.sh"  workingDirectory="%instanceDir%">
                        <arg>--variables z,salt %outputFile% %outputSalt%</arg>
                        <checkOutput file="%outputSalt%" />
                </action>
                <action exe="../bin/profile.sh"  workingDirectory="%instanceDir%">
                        <arg>--variables z,temp %outputFile% %outputTemp%</arg>
                        <checkOutput file="%outputTemp%" />
                </action>

                <action exe="../bin/profile.sh"  workingDirectory="%instanceDir%">
                        <arg>--variables z,eps %outputFile% %outputEps%</arg>
                        <checkOutput file="%outputEps%" />
                </action>
                <action exe="../bin/profile.sh"  workingDirectory="%instanceDir%">
                        <arg>--variables z,u,v %outputFile% %outputVelo%</arg>
                        <checkOutput file="%outputVelo%" />
                </action>
                <!-- write file to compare with observations files -->
                <action exe="../bin/profilemean.sh"  workingDirectory="%instanceDir%">
                        <arg>--variables %meanVar% --depth1 0.0 --depth2 15.0  %outputFile% %outputMeanTop%</arg>
                        <checkOutput file="%outputMeanTop%" />
                </action>
                <action exe="../bin/profilemean.sh"  workingDirectory="%instanceDir%">
                        <arg>--variables %meanVar% --depth1 20.0 --depth2 40.0  %outputFile% %outputMeanMid%</arg>
                        <checkOutput file="%outputMeanMid%" />
                </action>
                <action exe="../bin/profilemean.sh"  workingDirectory="%instanceDir%">
                        <arg>--variables %meanVar% --depth1 50.0 --depth2 75.0  %outputFile% %outputMeanBot%</arg>
                        <checkOutput file="%outputMeanBot%" />
                </action>
     	</additionalComputeActions>

		<finalizeActions></finalizeActions>

	</run>


	<inputOutput>

                <!-- manipulate namelists to start model -->
		<dataObject className="org.openda.model_gotm.GotmNmlFile">
			<file>%inputFile%</file>
			<id>input</id>
			<arg></arg>
		</dataObject>

		<dataObject className="org.openda.model_gotm.GotmNmlFile">
			<file>%inputFileTurb%</file>
			<id>inputTurb</id>
			<arg></arg>
		</dataObject>
		
		<dataObject className="org.openda.model_gotm.GotmMeteoFile">
			<file>%inputFileMeteo%</file>
			<id>inputMeteo</id>
			<arg></arg>
		</dataObject>
		
		<dataObject className="org.openda.model_gotm.GotmProfileFile">
			<file>%outputTemp%</file>
			<id>outTemp</id>
			<arg></arg>
		</dataObject>
		<dataObject className="org.openda.model_gotm.GotmProfileFile">
			<file>%outputSalt%</file>
			<id>outSalt</id>
			<arg></arg>
		</dataObject>
		<dataObject className="org.openda.model_gotm.GotmProfileFile">
			<file>%outputEps%</file>
			<id>outEps</id>
			<arg></arg>
		</dataObject>
		<dataObject className="org.openda.model_gotm.GotmProfileFile">
			<file>%outputVelo%</file>
			<id>outVelo</id>
			<arg></arg>
		</dataObject>
		<dataObject className="org.openda.model_gotm.GotmProfileFile">
			<file>%outputMeanTop%</file>
			<id>meanTempTop</id>
			<arg></arg>
		</dataObject>
		<dataObject className="org.openda.model_gotm.GotmProfileFile">
			<file>%outputMeanMid%</file>
			<id>meanTempMid</id>
			<arg></arg>
		</dataObject>
		<dataObject className="org.openda.model_gotm.GotmProfileFile">
			<file>%outputMeanBot%</file>
			<id>meanTempBot</id>
			<arg></arg>
		</dataObject>
		<dataObject className="org.openda.model_gotm.GotmProfileFile">
			<file>%outputEps%</file>
			<id>noise</id>
			<arg></arg>
		</dataObject>		
<!-- 		<dataObject className="org.openda.model_gotm.GotmMeteoFile"> -->
<!-- 			<file>%inputFileMeteo%</file> -->
<!-- 			<id>noise</id> -->
<!-- 			<arg></arg> -->
<!-- 		</dataObject> -->

<!-- 		<dataObject className="org.openda.model_gotm.GotmProfileFile">
			<file>%outputMean%</file>
			<id>meanVar</id>
			<arg></arg>
		</dataObject> -->

        <dataObject className="org.openda.exchange.dataobjects.NetcdfDataObject">
            <file>%outputFile%</file>
            <id>output</id>
            <arg>true</arg>
            <arg>false</arg>
        </dataObject>

	</inputOutput>

</blackBoxWrapperConfig>

=== OpenDA-Association/OpenDA/core/java/test/org/openda/blackbox/wrapper/testData/restartSecondPart/bbWrapperConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<blackBoxWrapperConfig xmlns="http://www.openda.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openda.org http://schemas.openda.org/blackBoxWrapperConfig.xsd">

	<!-- declare all the used aliases, specify the prefix and suffix of an alias key in a variable  -->

	<aliasDefinitions defaultKeyPrefix="%" defaultKeySuffix="%" >
		<alias key="instanceDir"/>
		<alias key="templateDir"/>
		<alias key="binDir"/>
		<alias key="noosfile_1"/>
		<alias key="noosfile_2"/>
		<alias key="noosfile_3"/>
        <alias key="statefile"/>
	</aliasDefinitions>

	<run>

		<!-- for each model instance, the template directory will be cloned to create the instance directory -->
		<initializeActionsUsingDirClone instanceDir="%instanceDir%%instanceNumber%" templateDir="%templateDir%"/>

		<!-- computation actions -->
		<!-- define actions relative to config dir. -->
		<computeActions>
			<action workingDirectory="%instanceDir%" windowsExe="./%binDir%/compute.bat" linuxExe="./%binDir%/compute.sh">
			<arg>%instanceDir%%instanceNumber%</arg>
			</action>
		</computeActions>

		<!-- actions to finalize (e.g. cleanup) an instance -->
		<finalizeActions/>

	</run>

	<inputOutput>

		<!-- noos time series 1 -->

		<ioObject className="org.openda.exchange.ioobjects.NoosTimeSeriesIoObject">
			<file>%noosfile_1%</file>
			<id>noosfile_1</id>
		</ioObject>

		<!-- noos time series 2 -->

		<ioObject className="org.openda.exchange.ioobjects.NoosTimeSeriesIoObject">
			<file>%noosfile_2%</file>
			<id>noosfile_2</id>
		</ioObject>

		<!-- noos time series 3 -->

		<ioObject className="org.openda.exchange.ioobjects.NoosTimeSeriesIoObject">
			<file>%noosfile_3%</file>
			<id>noosfile_3</id>
		</ioObject>

		<!-- simple state file -->

		<dataObject className="org.openda.blackbox.wrapper.DummyState">
			<file>%statefile%</file>
			<id>statefile</id>
		</dataObject>

	</inputOutput>

</blackBoxWrapperConfig>

=== OpenDA-Association/OpenDA/model_dflowfm_blackbox/tests/simple_waal_salt_kalman/stochModel/dflowfmWrapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<blackBoxWrapperConfig xmlns="http://www.openda.org"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="http://www.openda.org http://schemas.openda.org/blackBoxWrapperConfig.xsd">

    <!-- declare all the used aliases, specify the prefix and suffix of an alias key in a variable  -->
    <aliasDefinitions defaultKeyPrefix="%" defaultKeySuffix="%">
        <alias key="exedir"/>
        <alias key="instanceDir"/>
        <alias key="templateDir"/>
        <alias key="outputdir"/>
        <alias key="runid"/>
        <alias key="frictionCoefFile"/>
        <alias key="mdufile"/>
        <alias key="mapfile"/>
        <alias key="hisfile"/>
        <alias key="dimrfile"/>
    </aliasDefinitions>

    <run>

        <!-- for each model instance, the template directory will be cloned to create the instance directory -->
        <initializeActionsUsingDirClone instanceDir="%instanceDir%%instanceNumber%" templateDir="%templateDir%"/>

        <computeActions>
            <action workingDirectory="%instanceDir%" linuxExe="%exedir%/start_dimr.sh" windowsExe="%exedir%/start_dimr.bat">
                <arg>%dimrfile%</arg>
                <checkOutput file="%outputdir%/%hisfile%"/>
                <checkOutput file="%outputdir%/%mapfile%"/>
            </action>
            <action className="org.openda.utils.io.FileCopier" workingDirectory="%instanceDir%">
                <arg>%outputdir%/%mapfile%</arg>
                <arg>%mapfile%</arg>
            </action>
        </computeActions>

        <finalizeActions/>

    </run>

    <inputOutput>
        <dataObject className="org.openda.model_dflowfm.DFlowFMTimeInfo">
            <file>%mdufile%</file>
            <id>mdufile</id>
        </dataObject>
        <dataObject className="org.openda.model_dflowfm.DFlowFMRestartFileWrapper">
            <file>%mapfile%</file>
            <id>mapfile</id>
        </dataObject>
        <dataObject className="org.openda.exchange.dataobjects.NetcdfDataObject">
            <file>%outputdir%/%hisfile%</file>
            <id>hisfile</id>
            <arg>true</arg>
            <arg>false</arg>
        </dataObject>
        <dataObject className="org.openda.model_dflowfm.DFlowFMTimeSeriesDataObject">
            <file>%mdufile%</file>
            <id>boundaries</id>
        </dataObject>
    </inputOutput>

</blackBoxWrapperConfig>
