=== OpenDA-Association/OpenDA/core/xmlSchemas/observation/noosObservations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<!--W3C Schema generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<xs:schema xmlns:openda="http://www.openda.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.openda.org" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="timeSeries">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="status" use="optional" default="use">
						<xs:annotation>
							<xs:documentation>Set the status of this timeseries. Possible values are 'use', 'validate', and 'ignore'.</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="use"/>
								<xs:enumeration value="validate"/>
								<xs:enumeration value="ignore"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="standardDeviation" type="xs:float" use="optional" default="0.05">
						<xs:annotation>
							<xs:documentation>Specify the observational error standard deviation of this timeseries, that is independent of the value of the observations. The value is given in the same units as the observations.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="relativeStandardDeviation" type="xs:float" use="optional" default="0.0">
						<xs:annotation>
							<xs:documentation>Specify the part of the observational error standard deviation that is proportional to the observed value. A value of 0.1 adds an error of 10percent to the standard deviation. The errors remain additive.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="quantity" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>Quantity being observed, e.g. waterlevel, etc.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="unit" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>Unit of measurement in which the timeseries data is written.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="source" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>Source of data.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="timezone" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>Timezone in which data is written.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="height" type="xs:string" use="optional"/>
					<xs:attribute name="id">
						<xs:annotation>
							<xs:documentation>Identity of the observation.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="location" use="optional">
						<xs:annotation>
							<xs:documentation>Name of observing station.</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string"/>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="position" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>Coordinate of the position of the observing station.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="minValue">
						<xs:annotation>
							<xs:documentation>Minimum value for observation selection.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="maxValue">
						<xs:annotation>
							<xs:documentation>Maximum value for observation selection.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="minDateTime">
						<xs:annotation>
							<xs:documentation>Begin time for observation selection.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="maxDateTime">
						<xs:annotation>
							<xs:documentation>End time for observation selection</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="noosObserver">
		<xs:annotation>
			<xs:documentation>Configuration of NOOS type observer. The observation data is available in different file for different observing location. Here the available observation files are listed. The properties of each file are by default read directly from the files, except 'status' and 'standardDeviation'. The properties can be overwritten by specifying the relevant attributes of the timeSeries element in this xml file.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:annotation>
					<xs:documentation>Sequence of observed data timeseries.</xs:documentation>
				</xs:annotation>
				<xs:element ref="openda:timeSeries" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Specify the file name of the NOOS data timeseries. The path is written relative to the directory where this xml file is stored.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== OpenDA-Association/OpenDA/model_mikeshe/tests/Karup/XML/stochobserver/StochObsConfigEnKF.xml
<?xml version="1.0" encoding="UTF-8"?>
<noosObserver xsi:schemaLocation="http://www.openda.org http://schemas.openda.org/observation/noosObservations.xsd" xmlns:openda="http://www.openda.org" xmlns:xsi="http://www.w3.org/20.2/XMLSchema-instance">

	<timeSeries status="use" standardDeviation="0.2">
		head1.txt
	</timeSeries>

		<timeSeries status="use" standardDeviation="0.2">
		head2.txt
	</timeSeries>

		<timeSeries status="use" standardDeviation="0.2">
		head3.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head4.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head5.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head6.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head7.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head8.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head9.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head10.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head11.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head12.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head13.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head14.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head15.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head16.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head17.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head18.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head19.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head20.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head21.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head22.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head23.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head24.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head25.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head26.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head27.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head28.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head29.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head30.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head31.txt
	</timeSeries>
	
			<timeSeries status="use" standardDeviation="0.2">
		head32.txt
	</timeSeries>
	
				<timeSeries status="use" standardDeviation="0.2">
		head33.txt
	</timeSeries>
	
				<timeSeries status="use" standardDeviation="0.2">
		head34.txt
	</timeSeries>
	
				<timeSeries status="use" standardDeviation="0.2">
		head35.txt
	</timeSeries>
	
	
	










	
	</noosObserver>
