=== OpenDA-Association/OpenDA/core/xmlSchemas/noiseModels/mapsNoiseModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.openda.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.openda.org" elementFormDefault="qualified">
	<xs:include schemaLocation="noiseModelSharedTypes.xsd"/>
	<xs:simpleType name="coordinateAxisXML">
		<xs:annotation>
			<xs:documentation>Definition of the points along a coordinate axis (all points, or: start,next,...,end)</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9.,\- ]+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="noiseGridTypeXML">
		<xs:restriction base="xs:string">
			<xs:enumeration value="cartesian"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="noiseGridCoordSystemXML">
		<xs:restriction base="xs:string">
			<xs:enumeration value="xy"/>
			<xs:enumeration value="wgs84"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="noiseGridXML">
		<xs:annotation>
			<xs:documentation>output item containing a noise item of 2d-arrays with values generated by the noise model</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="x" type="coordinateAxisXML"/>
			<xs:element name="y" type="coordinateAxisXML"/>
		</xs:sequence>
		<xs:attribute name="type" type="noiseGridTypeXML" use="optional" default="cartesian">
			<xs:annotation>
				<xs:documentation>The type of grid</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="coordinates" type="noiseGridCoordSystemXML" use="optional" default="xy">
			<xs:annotation>
				<xs:documentation>The coordinate system of the grid</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="separable" type="xs:boolean" use="optional" default="false">
			<xs:annotation>
				<xs:documentation>Can correlated noise be generated for x and y axis seperately?</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="horizontalCorrelationScaleUnitXML">
		<xs:restriction base="xs:string">
			<xs:enumeration value="cm"/>
			<xs:enumeration value="m"/>
			<xs:enumeration value="km"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="noiseItemXML">
		<xs:annotation>
			<xs:documentation>output item containing a noise item of 2d-arrays with values generated by the noise model</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="grid" type="noiseGridXML"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The identifier for the noise item</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="initialValue" type="xs:double" use="optional" default="0.0">
			<xs:annotation>
				<xs:documentation>The initial value for the generated noise</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="standardDeviation" type="xs:double" use="required">
			<xs:annotation>
				<xs:documentation>The standard deviation for the generated noise</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="timeCorrelationScale" type="xs:double" use="required">
			<xs:annotation>
				<xs:documentation>Time interval speficying the time correlation between the consecutive values</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="timeCorrelationScaleUnit" type="timeCorrelationScaleUnitXML" use="optional" default="days">
			<xs:annotation>
				<xs:documentation>The unit for the time correlation scale</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="horizontalCorrelationScale" type="xs:double" use="required">
			<xs:annotation>
				<xs:documentation>Interval speficying the horizontal spatial correlation between the consecutive values</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="horizontalCorrelationScaleUnit" type="horizontalCorrelationScaleUnitXML" use="optional" default="m">
			<xs:annotation>
				<xs:documentation>The unit for the horizontal correlation scale</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="quantity" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>The quantity contained in the noise item</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="unit" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>The unit of the quantity contained in the noise item</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="timezone" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Time zone for the noise noise item (GMT, CET, etc ...). Currently not supported</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="height" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Deprecated</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="mapsNoiseModelConfigXML">
		<xs:sequence>
			<xs:element name="simulationTimespan" type="simulationTimespanXML"/>
			<xs:element name="noiseItem" type="noiseItemXML" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="mapsNoiseModelConfig" type="mapsNoiseModelConfigXML">
		<xs:annotation>
			<xs:documentation>Configuration for OpenDA's noise model</xs:documentation>
		</xs:annotation>
	</xs:element>
</xs:schema>

=== OpenDA-Association/OpenDA/model_delft3d/tests/d3d_3Dlake_EnKF_states/stochModel/noiseModelConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapsNoiseModelConfig xmlns="http://www.openda.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openda.org http://schemas.openda.org/noiseModels/mapsNoiseModel.xsd">
	<simulationTimespan timeFormat="dateTimeString">201506010000,201506010100,...,201506030000</simulationTimespan>
	
	<noiseItem id="windu_noise" quantity="wind-u" unit="m/s" height="10.0"
	 standardDeviation="1.0" timeCorrelationScale="6.0" timeCorrelationScaleUnit="hours" 
	 initialValue="0.0" horizontalCorrelationScale="100." horizontalCorrelationScaleUnit="m" >
	 	<grid type="cartesian" coordinates="xy">
	 		<x>694980.,695230.,...,700230.</x>
	 		<y>153788.,154038.,...,158538.</y>
	 	</grid>
	</noiseItem>
	
	<noiseItem id="windv_noise" quantity="wind-v" unit="m/s" height="10.0"
	 standardDeviation="1.0" timeCorrelationScale="6.0" timeCorrelationScaleUnit="hours" 
	 initialValue="0.0" horizontalCorrelationScale="100." horizontalCorrelationScaleUnit="m">
	 	<grid type="cartesian" coordinates="xy">
	 		<x>694980.,695230.,...,700230.</x>
	 		<y>153788.,154038.,...,158538.</y>
	 	</grid>
	</noiseItem>
	
</mapsNoiseModelConfig>
